# Generated by Django 2.1.5 on 2022-11-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
    ]
