# Generated by Django 2.1.5 on 2022-11-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221113_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='performer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
