# Generated by Django 2.1.5 on 2022-11-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_event_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_seat_nr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_stand_nr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_seat_nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_stand_nr',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
